name: Unit Tests with PyTest 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install venv
        run: |
          python -m venv lsys-venv
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run pytest 
        run: |
          pytest 
